const SENTENCES=[
"i had a long walk outside this morning and it was the perfect way to start the day the air felt crisp and fresh against my face as i stepped into the cool morning breeze the birds were already singing their morning songs and i felt completely awake and alive",
"it was a beautiful sunny day with not a cloud in the sky and the temperature was just right so i decided to take my time walking through the neighborhood enjoying the perfect weather conditions that made everything feel so right",
"the air felt fresh and cool with a gentle breeze that carried the scent of cut grass and distant flowers i took deep breaths filling my lungs with the clean morning air that just felt absolutely rejuvenating",
"i stopped at the corner coffee shop that had become my favorite spot the line was short and the barista remembered my usual order immediately which made me feel right at home",
"the coffee was warm and rich with perfect notes of chocolate and caramel that melted in my mouth and i savored every single sip like it was a small luxury i truly deserved",
"i sat outside on the patio bench for a good while people watching and listening to the distant city sounds while the warmth of the sun slowly moved across my face and warmed my entire body",
"the street was not too busy which was exactly what i needed there was just the right amount of traffic and activity to feel alive without being overwhelming or chaotic",
"an old neighbor driving by waves at me with a big smile on his face and i wave back feeling a strong sense of community and belonging in this neighborhood i call home",
"i waved back and smiled thinking about how nice it is to know the people around you and how even small interactions can brighten your entire day unexpectedly",
"the breeze felt nice and gentle on my face as i continued walking the scent of pine trees and wet earth after last night's rain filled the air completely",
"i walked back home slowly enjoying the peace and quiet that only a residential street can offer during the middle of the day",
"the grocery store opened its doors early at eight o'clock and i was one of the first people to walk through the automatic doors feeling ready for whatever i needed",
"i picked up some fresh bread that was still warm from the oven the smell immediately filled my bag and i could barely contain my excitement",
"the bread smelled really good and slightly sweet from the baking process making my mouth water just thinking about having it with dinner tonight",
"i bought a carton of milk too along with the bread and eggs because i needed to restock my refrigerator for the week ahead",
"the checkout line moved surprisingly fast which was such a relief after a long week and the cashier was friendly and made the whole experience better",
"i was home by nine o'clock exactly feeling accomplished and tired in the best possible way after a productive morning well spent",
"i made breakfast in the kitchen starting with two eggs sunny side up that sizzled in the pan perfectly",
"i ate at the table by the window watching the world wake up outside while my food got cold but i didn't really mind",
"the morning sun came through the glass window casting beautiful patterns of light and shadow across the kitchen floor and table",
"the apartment felt quiet and calm after i returned from my walk which was exactly what my mind and body needed",
"i cleaned up the kitchen quickly putting everything in its place and wiping down the counters until they sparkled",
"my plan for today was actually quite simple accomplish a few small tasks and then relax and unwind",
"i needed to fix a small lamp that had been broken for weeks and i finally decided to tackle the project head on",
"the lamp worked after just one try which was surprising and i felt a rush of satisfaction and pride",
"it had just been unplugged the whole time which made me feel a bit silly for not checking the simplest solution first",
"i laughed at how easy it was once i realized the answer had been right in front of me the whole time",
"i took a long hot shower that felt like pure heaven under the streaming hot water",
"the water relaxed my shoulders and melted away all the tension i had been carrying for days",
"i put on my most comfortable clothes that were soft and loose and perfect for lounging around the apartment",
"then i sat down on the couch and checked my phone seeing several notifications that i needed to address",
"there was a text message from my best friend asking if i wanted to grab lunch soon",
"she wanted to meet at the cafe we always go to because the food there is always excellent and the service is great",
"i said yes right away without even thinking because i really needed to see her and catch up",
"we met at the usual table by the window that we both love and have claimed as our regular spot",
"the cafe was not too crowded which was perfect for having a long and meaningful conversation",
"we ordered the same things we always order the turkey sandwich and iced tea never change what works",
"the soup of the day was tomato basil and it looked absolutely delicious from the menu description",
"it came with a warm crusty bread roll on the side that i immediately broke apart and started eating",
"we talked about our weeks and all the things we had been up to since we last saw each other",
"she told me about her exciting trip to another city that she took last month and all the adventures she had",
"it sounded like a lot of fun and i felt a little bit jealous but mostly happy for her experiences",
"i told her all about the small lamp fix i did around the house and how satisfying it was to repair things",
"we laughed for a solid thirty minutes about everything and nothing which was exactly what i needed",
"lunch lasted much longer than planned because the conversation was just that good and engaging",
"nobody wanted to leave the cafe yet because we were having such a wonderful time together",
"we walked hand in hand through the park after lunch the weather was still perfect and the sky was clear",
"the benches were still empty and we found a nice spot under the shade of a big old tree",
"the leaves rustled softly in the gentle breeze making a beautiful sound that matched our mood",
"we watched a dog chase a ball across the open field repeatedly with absolute joy and excitement",
"its owner threw it again and again without getting tired and the dog gave absolutely everything he had",
"the dog never got tired even after dozens of throws which was impressive and inspiring to watch",
"i felt really glad that i had such a slow and peaceful day where nothing stressful happened",
"i said goodbye to my friend around two o'clock when the lunch feeling was absolutely perfect",
"the walk home was peaceful and quiet with the golden hour light making everything look magical",
"the sky was clear and blue with just a few white clouds drifting slowly by in the distance",
"i could hear birds singing their hearts out from the trees and it just felt like the perfect day",
"the neighborhood was very quiet and calm which was exactly what i needed after such a long week",
"i opened the door to my apartment and stepped inside feeling an instant sense of relief and comfort",
"my cat was sleeping peacefully on the couch in her favorite sunny spot and i smiled softly",
"she did not even open her eyes when i walked in which was fine because i just wanted to be near her",
"i sat down next to her on the cushion and leaned my head against the backrest enjoying the moment",
"she stretched and rolled over onto her side revealing her soft belly completely by accident",
"i pet her gentle ears and down her back which made her purr loudly and vibrate through my hands",
"the afternoon light was warm and golden pouring through the windows and creating beautiful patterns",
"i made another cup of tea that was perfectly steeped and exactly what i needed at that moment",
"i sat by the window with my tea watching the world go by slowly and peacefully",
"the steam from the hot tea rose up in a perfect spiral into the cool afternoon air",
"i watched the street below where people were going about their evening routines and errands",
"a kid rode by on a bright red bike with streamers flying off the handlebars flapping in the wind",
"a mail truck turned the corner up the street making its delivery rounds for the neighborhood",
"the day was moving along nicely and i felt content with how everything was unfolding",
"i decided to start a small drawing in my sketchbook that i had been wanting to work on",
"i drew the big tree from the park that i had seen earlier and tried to capture its essence",
"it was not perfect by any means but i liked it anyway because it was mine and expressed my vision",
"i carefully tore the page out and put it up on my fridge using a colorful magnet i had bought",
"the evening news came on soon after i finished my tea and i watched for just a little bit",
"i watched for a little bit to catch the weather report and any important headlines that mattered",
"then i began making dinner because i was getting hungry and needed to refuel for the rest of the evening",
"i chopped some fresh vegetables for the salad i was planning to make and the knife was sharp",
"the pan sizzled as i added olive oil and the sound was music to my ears and signaled the start",
"i stirred the rice slowly while it cooked and absorbed all the flavors and seasonings i added",
"dinner was ready by seven o'clock exactly and the aroma filled the entire apartment",
"it smelled even better than lunch had and i felt so lucky to have such wonderful meals",
"i sat down and ate slowly savoring every bite and feeling grateful for the nourishment",
"the sauce was just right with the perfect balance of spices and herbs that i had carefully selected",
"i saved half of the delicious food for tomorrow's lunch because i knew i would be hungry again",
"i did the dishes right away after eating so the kitchen would be clean and ready for tomorrow",
"the kitchen was neat and tidy after that with everything in its proper place and organized",
"i stepped out onto my balcony that overlooks the whole city street and neighborhood below",
"the evening air was cool and fresh after the hot day finally starting to wind down",
"the street lights came on below one by one creating a beautiful path of light down the road",
"i watched them flicker to life one by one and thought about how the world keeps moving",
"a neighbor was walking her dog on the sidewalk down below and i waved from my balcony",
"we said hello from a distance across the street and i felt that sense of community again",
"i stayed out on the balcony until it got fully dark and the sky turned into a beautiful canvas",
"the stars slowly appeared above one by one becoming more and more numerous as time passed",
"i went back inside when i started to feel a little bit cold from the evening breeze",
"the apartment glowed with warm light from all the lamps and made everything feel cozy and inviting",
"my cat waited by her food bowl in the kitchen and i immediately filled it up for the night",
"i locked the front door and checked all the windows were secure before anything could happen",
"i changed into my favorite soft pajamas that were comfortable and perfect for sleeping",
"i sat down in bed with a really good book that i had been excited to start for weeks",
"the book was getting really good and i was completely hooked into the plot and characters",
"my eyes grew heavy around ten o'clock and i knew it was time to stop reading for the night",
"i marked my page with a colorful bookmark i had collected and set the book gently on my nightstand",
"i turned off the lamp by the bed and the room instantly went very dark and quiet",
"i lay flat on my back and took a deep breath filling my lungs with fresh night air",
"the day had felt long and full of so many wonderful experiences and i was exhausted in a good way",
"nothing unusual had happened which was exactly what made the day so special and relaxing",
"but small things made it good like the coffee the conversation the walk and the peace i felt",
"a good coffee and a long talk with a friend are really all i need to feel refreshed and renewed",
"a warm lunch and a quiet walk through the neighborhood always puts me in a better mood instantly",
"i smiled in the darkness as i drifted off to sleep with a happy heart and contented mind",
"tomorrow will probably be another good day filled with new experiences and unexpected surprises."
];

const SENTENCE_COUNT=SENTENCES.length;
let playOrder=[];
function buildOrder(){
  playOrder=[];
  for(let i=0;i<SENTENCE_COUNT;i++)playOrder.push(i);
  for(let i=playOrder.length-1;i>0;i--){
    const j=Math.floor(Math.random()*(i+1));
    const t=playOrder[i];playOrder[i]=playOrder[j];playOrder[j]=t;
  }
}
buildOrder();
let orderIndex=0;
function nextSentence(){
  if(orderIndex>=playOrder.length)buildOrder();
  return SENTENCES[playOrder[orderIndex++]];
}