const SENTENCES=[
"i like to wake up early on saturday mornings.",
"my mom makes the best pancakes in the world.",
"we watch a movie every friday night.",
"the dog loves to play fetch in the backyard.",
"i had a really long day at school today.",
"pizza and tacos are my favorite foods.",
"my brother plays video games all the time.",
"the weather is perfect for a walk outside.",
"i need to buy some milk at the store.",
"my sister is learning how to ride a bike.",
"we went to the beach last weekend.",
"the new song on the radio is so good.",
"i forgot my homework at home again.",
"grandpa told us a funny story at dinner.",
"the cat knocked over my water glass again.",
"i like to read comics before going to sleep.",
"let us go play basketball at the park.",
"my phone is running out of battery again.",
"ice cream tastes great on a hot day.",
"we have a big test in math tomorrow.",
"my friend and i ride our bikes to school.",
"the sunset looked so pretty tonight.",
"i cleaned my room after much nagging.",
"dad taught me how to change a tire.",
"we ordered pizza because no one wanted to cook.",
"my grandma makes cookies for every holiday.",
"the bus was late again this morning.",
"i scored two goals in the game today.",
"my little sister keeps taking my stuff.",
"we are going camping with our cousins.",
"the new kid in class is pretty cool.",
"i like hot chocolate on cold days.",
"my bed is the most comfortable place ever.",
"we decorated the house for the celebration.",
"i finished all my chores before noon.",
"the music at the party was really loud.",
"my favorite team won the big game.",
"i watch funny videos when i am bored.",
"we have a new teacher this year.",
"the burger place opened around the corner.",
"my uncle has the coolest car in town.",
"i practice my guitar every day after school.",
"we built a fort with blankets and chairs.",
"the pool water is nice and cool today.",
"i woke up late and almost missed breakfast.",
"my dog makes me laugh when he runs.",
"we share snacks during the movie.",
"i need to copy down the notes from class.",
"the air smells like rain outside.",
"my mom gave me a ride to practice.",
"i love the feeling of new school shoes.",
"we had pasta for dinner again tonight.",
"the library lets me borrow three books.",
"my cousin taught me a new trick.",
"i always lose my pencil at school.",
"the neighbors got a new trampoline.",
"we sang songs on the way home.",
"i want a snack but we are out of them.",
"the game was tied until the last minute.",
"my best friend moved next door to me.",
"the teacher said my essay was good.",
"we planted flowers in the front yard.",
"i get scared of the dark sometimes.",
"my favorite shirt has a rip in it.",
"we played tag until it got dark.",
"the remote control is missing again.",
"i like the smell of fresh bread.",
"my mom and i went shopping for groceries.",
"the homework took forever to finish.",
"we saw a rainbow after the storm.",
"my brother snores really loud at night.",
"the fair has the best fried treats.",
"i can finally tie my shoes by myself.",
"we stayed up late watching a movie.",
"the store gives free samples on weekends.",
"my dad makes great scrambled eggs.",
"we learn a new topic in class tomorrow.",
"my feet hurt from walking all day.",
"the kitten fit inside a coffee mug.",
"i want to go to the arcade this weekend.",
"we had a fire drill at school today.",
"my mom says my room looks like a mess.",
"the smoothie place makes them fresh daily.",
"i ride the bus with my neighbor.",
"we played board games on the rainy day.",
"my shoes are a little too tight now.",
"the teacher passed out the graded papers.",
"i helped wash the dishes after dinner.",
"we are getting a new couch this week.",
"the dogs bark every time the mail comes.",
"i made a drawing for my mom.",
"we went to the mall to get new clothes.",
"my head hurts from staying up late.",
"the park has a huge slide that is fast.",
"i watched two episodes of my show.",
"my friend knows every word to the song.",
"we shared a seat on the crowded ride.",
"the ice cream truck came down our street.",
"i forgot my water bottle at practice.",
"my jacket is the one with the hood.",
"we collected leaves and made a big pile.",
"the baby next door cries a lot at night.",
"i put my homework in my backpack finally.",
"the movie theater is five minutes from here.",
"we took a long walk after dinner.",
"i have a new book to finish this week.",
"the gym class had a relay race today.",
"my dad says practice makes perfect.",
"we laughed until our stomachs hurt.",
"i saved up my allowance for a new game.",
"the bakery downtown smells amazing in the morning.",
"my sister and i share a big closet.",
"we watched the sunrise from the roof.",
"the test was easier than i expected.",
"i always take the stairs at the mall.",
"my mom packed me a bag of snacks.",
"we drew pictures of our families in class.",
"the water in the lake is really clear.",
"i want to learn a new language next year."
];

const SENTENCE_COUNT=SENTENCES.length;
let playOrder=[];
function buildOrder(){
  playOrder=[];
  for(let i=0;i<SENTENCE_COUNT;i++)playOrder.push(i);
  for(let i=playOrder.length-1;i>0;i--){
    const j=Math.floor(Math.random()*(i+1));
    const t=playOrder[i];playOrder[i]=playOrder[j];playOrder[j]=t;
  }
}
buildOrder();
let orderIndex=0;
function nextSentence(){
  if(orderIndex>=playOrder.length)buildOrder();
  return SENTENCES[playOrder[orderIndex++]];
}
