const SENTENCES=[
"i had a walk outside this morning.",
"it was a nice day for it.",
"the air felt fresh and cool.",
"i stopped at the corner for coffee.",
"the coffee was warm and sweet.",
"i sat outside for a while.",
"the street was not too busy.",
"an old neighbor waved at me.",
"i waved back and smiled.",
"the breeze felt nice on my face.",
"i walked back home slowly.",
"the grocery store opened early.",
"i picked up some fresh bread.",
"the bread smelled really good.",
"i bought a carton of milk too.",
"the checkout line moved fast.",
"i was home by nine o'clock.",
"i made breakfast in the kitchen.",
"two eggs and a piece of toast.",
"i ate at the table by the window.",
"the morning sun came through the glass.",
"the apartment felt quiet and calm.",
"i cleaned up the kitchen quickly.",
"my plan for today was simple.",
"i needed to fix a small lamp.",
"the lamp worked after one try.",
"it had just been unplugged.",
"i laughed at how easy it was.",
"i took a long hot shower.",
"the water relaxed my shoulders.",
"i put on comfortable clothes.",
"then i checked my phone.",
"there was a text from my friend.",
"she wanted to meet for lunch.",
"i said yes right away.",
"we met at the usual place.",
"the cafe was not too crowded.",
"we ordered the same things again.",
"the soup of the day was tomato.",
"it came with a warm roll.",
"we talked about our week.",
"she told me about her trip.",
"it sounded like a lot of fun.",
"i told her about my small lamp fix.",
"we laughed for a long time.",
"lunch lasted longer than planned.",
"nobody wanted to leave yet.",
"we walked to the park after lunch.",
"the benches were still empty.",
"we sat under a big tree.",
"the leaves made a soft sound.",
"we watched a dog chase a ball.",
"its owner threw it again and again.",
"the dog never got tired.",
"i felt glad for the slow day.",
"i said goodbye around two.",
"the walk home was peaceful.",
"the sky was clear and blue.",
"a few white clouds drifted by.",
"i could hear birds singing.",
"the neighborhood was very quiet.",
"i opened the door to my place.",
"my cat was sleeping on the couch.",
"she did not even open her eyes.",
"i sat down next to her.",
"she stretched and rolled over.",
"i petted her until she purred.",
"the afternoon light was warm.",
"i made another cup of tea.",
"i sat by the window with it.",
"the steam rose from the cup.",
"i watched the street below.",
"a kid rode by on a red bike.",
"a mail truck turned the corner.",
"the day was moving along nicely.",
"i started a small drawing.",
"i drew the tree from the park.",
"it was not perfect but i liked it.",
"i put it up on the fridge.",
"the evening news came on soon.",
"i watched for a little bit.",
"then i began making dinner.",
"i chopped some vegetables for it.",
"the pan sizzled as i cooked.",
"i stirred the rice slowly.",
"dinner was ready by seven o'clock.",
"it smelled even better than lunch.",
"i sat down and ate slowly.",
"the sauce was just right.",
"i saved half for tomorrow.",
"i did the dishes right away.",
"the kitchen was neat after that.",
"i stepped out onto the balcony.",
"the evening air was cool.",
"the street lights came on below.",
"i watched them flicker to life.",
"a neighbor was walking her dog.",
"we said hello from a distance.",
"i stayed out until it got dark.",
"the stars slowly appeared above.",
"i went back in when i felt cold.",
"the apartment glowed with warm light.",
"my cat waited by her food bowl.",
"i filled it up for the night.",
"i locked the door and checked the windows.",
"i changed into my pajamas.",
"i read a few chapters in bed.",
"the book was getting really good.",
"my eyes grew heavy around ten.",
"i marked my page and set it down.",
"i turned off the lamp.",
"the room went very dark.",
"i lay flat and took a deep breath.",
"the day had felt long and full.",
"nothing unusual had happened.",
"but small things made it good.",
"a good coffee and a long talk.",
"a warm lunch and a quiet walk.",
"i smiled in the darkness.",
"tomorrow will probably be another good day."
];

const SENTENCE_COUNT=SENTENCES.length;
let playOrder=[];
function buildOrder(){
  playOrder=[];
  for(let i=0;i<SENTENCE_COUNT;i++)playOrder.push(i);
  for(let i=playOrder.length-1;i>0;i--){
    const j=Math.floor(Math.random()*(i+1));
    const t=playOrder[i];playOrder[i]=playOrder[j];playOrder[j]=t;
  }
}
buildOrder();
let orderIndex=0;
function nextSentence(){
  if(orderIndex>=playOrder.length)buildOrder();
  return SENTENCES[playOrder[orderIndex++]];
}